### ISSUE TITLE
Toasts are dismissed without being shown when there are more toasts than `maxVisibleToasts`

### ISSUE THREAD

**Issue by sproctor** [dokar3/compose-sonner#25]
I suppose I could handle this myself, but I think any users would appreciate the change.

My suggestion is that the duration for a toast should start when it is the top toast on the stack, instead of when it's created.

**Comment by dokar3** [comment]
Good idea, considering making this an option, as making it default might be annoying since we have to dismiss them (or wait for them to be dismissed) one by one.

**Comment by dokar3** [comment]
Done in #27

**Comment by sproctor** [comment]
That's great! Thanks for implementing this.

**Comment by dokar3** [comment]
You're welcome, will publish it after another PR is merged.

**Comment by dokar3** [comment]
The new version is out, please feel free to upgrade and try it out!
https://github.com/dokar3/compose-sonner/releases/tag/v0.3.3
