### ISSUE TITLE
Dismissing a toast with an `action` when using `listenMany` has a weird animation

### ISSUE THREAD

**Issue by sproctor** [dokar3/compose-sonner#26]
```kotlin
toastState.listenMany(
    errorMessages.map { entries ->
        entries.map { entry ->
            Toast(
                id = entry.key,
                message = entry.value.toString(),
                duration = ToasterDefaults.DurationLong,
                action = TextToastAction(
                    text = "Dismiss",
                    onClick = { toastState.dismiss(it.id) }
                )
            )
        }
    }
)
```

The toast is not equal to itself, because the `TextToastAction` is created each time. The `updateOrShow` has a problem in this case. I think showing a toast with the same `id` should leave it in place. That is, don't check if it's at the end and just always update it in place.

https://github.com/dokar3/compose-sonner/blob/f4a1f3d034e586e7d3086d9eee3eb732e6220cf3/sonner/src/commonMain/kotlin/com/dokar/sonner/ToasterState.kt#L152

**Comment by dokar3** [comment]
Thanks for investigating this. I was doing the reordering after updating the toast for some reason when writing this code, and about the reason, I can't recall it, that is a truly coding moment.
Anyway, the reordering seems unnecessary, will remove this if it doesn't break some feature.

**Comment by sproctor** [comment]
If someone needs to move a toast to the end, it's still possible by dismissing it first.
