### ISSUE TITLE
iOS implementation

### ISSUE THREAD

**Issue by shubhamsinghmutualmobile** [dokar3/compose-sonner#5]
Hey @dokar3, it's a cool library you've got going on here 👏 

As you mentioned in your comment (`iOS target. Waiting for contributors because I don't have any Apple devices to run`), I can try to help you out here as I have a Macbook. We can test the iOS implementation on an iOS simulator.

Would you like to create a new feature branch containing the iOS implementation that I can test out and give you any kind of feedback you'd like?

**Comment by dokar3** [comment]
Hi there, glad to hear you can help!
You can create an iOS branch and a pull request without asking! I'll merge it ASAP.
