### ISSUE TITLE
How do I display Toaster on top of Dialog?

### ISSUE THREAD

**Issue by Matcha-xiaobin** [dokar3/compose-sonner#87]
How do I display Toaster on top of Dialog?

When I pop up an AlertDialog on android with an action button on it, when the operation fails, I want the AlertDialog not to close, and use Toaster to pop up a prompt, currently Taster will be below the AlertDialog.

**Comment by suzhelan** [comment]
你是否找到了解决办法 我遇到了一个问题 toast是在屏幕底部展示的
